name: "Model check"
on:
  pull_request:
  push:
    branches:
      master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: workflow/nix-shell-action@v1
      with:
        packages: tlaplus
        script: |
          make test
